"""Add media_type and media_file to Section model

Revision ID: 057531b0f1c8
Revises: 9ca3025ff4fd
Create Date: 2025-06-04 17:36:44.466067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057531b0f1c8'
down_revision = '9ca3025ff4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('media_file', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_column('media_file')
        batch_op.drop_column('media_type')

    # ### end Alembic commands ###
