"""add certificate_path to Enrollment

Revision ID: 1a0f5134eddd
Revises: 0ac99b194e52
Create Date: 2025-07-03 02:44:01.006070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a0f5134eddd'
down_revision = '0ac99b194e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificates')
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_column('certificate_path')

    op.create_table('certificates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('enrollment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('certificate_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('issued_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('revoked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name='certificates_enrollment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='certificates_pkey'),
    sa.UniqueConstraint('certificate_id', name='certificates_certificate_id_key')
    )
    # ### end Alembic commands ###
