"""fresh start with all models

Revision ID: 339676828b10
Revises: 3bd34526992d
Create Date: 2025-04-26 08:21:34.105882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339676828b10'
down_revision = '3bd34526992d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=255), nullable=True))
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('enrollment_sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_attempt_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('enrollment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('section_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.Float(), nullable=True))
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=True))
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('created_at')
        batch_op.drop_column('active')

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('duration_minutes')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('progress')
        batch_op.drop_column('completed_at')

    with op.batch_alter_table('enrollment_sections', schema=None) as batch_op:
        batch_op.alter_column('section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('enrollment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('last_attempt_at')
        batch_op.drop_column('attempts')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
