"""add file_path to assignment_submissions

Revision ID: 36f04a4c8046
Revises: 8cfff9f9affb
Create Date: 2025-06-09 11:53:31.193851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f04a4c8046'
down_revision = '8cfff9f9affb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_submissions', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
