"""add is_blocked to enrollment

Revision ID: 4a8fbaf0fd21
Revises: 60898e264fa4
Create Date: 2026-07-28 13:46:31.971663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8fbaf0fd21'
down_revision = '60898e264fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('block_reason', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_enrollments_is_blocked'), ['is_blocked'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_is_blocked'))
        batch_op.drop_column('block_reason')
        batch_op.drop_column('is_blocked')

    # ### end Alembic commands ###
