"""Add completed_at to Enrollment model

Revision ID: 60898e264fa4
Revises: fc5c9045136a
Create Date: 2025-10-25 18:21:49.114620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60898e264fa4'
down_revision = 'fc5c9045136a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_title'), ['title'], unique=False)

    with op.batch_alter_table('enrollment_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollment_sections_completed'), ['completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollment_sections_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollment_sections_section_id'), ['section_id'], unique=False)

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_enrollments_completed'), ['completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_enrolled_at'), ['enrolled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_student_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_enrolled_at'))
        batch_op.drop_index(batch_op.f('ix_enrollments_course_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_completed'))
        batch_op.drop_column('completed_at')

    with op.batch_alter_table('enrollment_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollment_sections_section_id'))
        batch_op.drop_index(batch_op.f('ix_enrollment_sections_enrollment_id'))
        batch_op.drop_index(batch_op.f('ix_enrollment_sections_completed'))

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_title'))
        batch_op.drop_index(batch_op.f('ix_courses_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_courses_status'))
        batch_op.drop_index(batch_op.f('ix_courses_created_at'))

    # ### end Alembic commands ###
