"""Add bio and contact fields to User model

Revision ID: 646bc14fd147
Revises: 1a0f5134eddd
Create Date: 2025-10-05 17:26:59.617616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '646bc14fd147'
down_revision = '1a0f5134eddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contact', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('contact')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
