"""Add duration to Section

Revision ID: 885fe2d33365
Revises: c57be294d4a4
Create Date: 2025-05-23 09:59:09.521686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885fe2d33365'
down_revision = 'c57be294d4a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
