"""add course fields, rating model, and section video_url

Revision ID: 8cfff9f9affb
Revises: 057531b0f1c8
Create Date: 2025-06-05 14:49:04.721031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cfff9f9affb'
down_revision = '057531b0f1c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_image', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('intro_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('intro_video', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('teacher_bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('teacher_contact', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('resources', sa.Text(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('resources')
        batch_op.drop_column('teacher_contact')
        batch_op.drop_column('teacher_bio')
        batch_op.drop_column('intro_video')
        batch_op.drop_column('intro_text')
        batch_op.drop_column('banner_image')

    op.drop_table('ratings')
    # ### end Alembic commands ###
