"""Add sectjhgions to coursedfghjs

Revision ID: c57be294d4a4
Revises: 
Create Date: 2025-05-08 00:56:33.908261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c57be294d4a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('admin_feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pdf_filename', sa.String(length=120), nullable=True))

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_column('is_published')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('pdf_filename')
        batch_op.drop_column('admin_feedback')
        batch_op.drop_column('youtube_url')

    # ### end Alembic commands ###
