"""Add accreditation_name to Course

Revision ID: dbf3177e226d
Revises: 4a8fbaf0fd21
Create Date: 2026-07-31 14:54:09.990129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf3177e226d'
down_revision = '4a8fbaf0fd21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accreditation_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('accreditation_name')

    # ### end Alembic commands ###
