"""add profile_image to users

Revision ID: fc5c9045136a
Revises: f5c0790e5600
Create Date: 2025-10-19 14:08:59.282699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5c9045136a'
down_revision = 'f5c0790e5600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_announcements_course_id'))

    with op.batch_alter_table('assignment_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_submissions_type'))

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_assignments_coding'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_notifications_created_at'))
        batch_op.drop_index(batch_op.f('idx_notifications_read'))
        batch_op.drop_index(batch_op.f('idx_notifications_user_id'))

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_quiz_attempts_student'))

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_quiz_time_limit'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))

    with op.batch_alter_table('video_interactive_questions', schema=None) as batch_op:
        batch_op.alter_column('section_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('video_question_responses', schema=None) as batch_op:
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('video_subtitles', schema=None) as batch_op:
        batch_op.alter_column('section_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('video_watch_progress', schema=None) as batch_op:
        batch_op.alter_column('enrollment_section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_watch_progress', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('enrollment_section_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('video_subtitles', schema=None) as batch_op:
        batch_op.alter_column('section_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('video_question_responses', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('video_interactive_questions', schema=None) as batch_op:
        batch_op.alter_column('section_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_quiz_time_limit'), ['time_limit'], unique=False)

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_quiz_attempts_student'), ['student_id', 'quiz_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_notifications_read'), ['read'], unique=False)
        batch_op.create_index(batch_op.f('idx_notifications_created_at'), [sa.literal_column('created_at DESC')], unique=False)

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_assignments_coding'), ['is_coding_assignment'], unique=False)

    with op.batch_alter_table('assignment_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_submissions_type'), ['submission_type'], unique=False)

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_announcements_course_id'), ['course_id'], unique=False)

    # ### end Alembic commands ###
